#ifndef _ENV_H
#define _ENV_H

const char *API_URL = API_URL_MACRO;
const char *SSID = SSID_MACRO;
const char *WIFIPASS = WIFIPASS_MACRO;

const char *FIREBASE_API_KEY = FIREBASE_API_KEY_MACRO;
const char *FIREBASE_USER_EMAIL = FIREBASE_USER_EMAIL_MACRO;
const char *FIREBASE_RTDB_URL = FIREBASE_RTDB_URL_MACRO;
const char *FIREBASE_USER_PASSWORD = FIREBASE_USER_PASSWORD_MACRO;

#endif