#ifndef _BDA_ENV_H
#define _BDA_ENV_H

const char *BDA_API_URL = BDA_API_URL_MACRO;
const char *WIFI_SSID = WIFI_SSID_MACRO;
const char *WIFI_PASSWORD = WIFI_PASSWORD_MACRO;

const char *FIREBASE_API_KEY = FIREBASE_API_KEY_MACRO;
const char *FIREBASE_USER_EMAIL = FIREBASE_USER_EMAIL_MACRO;
const char *FIREBASE_RTDB_URL = FIREBASE_RTDB_URL_MACRO;
const char *FIREBASE_USER_PASSWORD = FIREBASE_USER_PASSWORD_MACRO;

#endif // _BDA_ENV_H